#name: home-system

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    env_file: n8n.env
    ports:
      - "5678:5678"
    volumes:
      - n8n-data:/home/node/.n8n
    networks:
      - home-system-net

volumes:
  n8n-data:

networks:
  home-system-net:
